app/db.py, app/main.py, docker-compose.yaml, requirements.txt
<br>
<br>
close #6 
<br>
<br>
- <br>
- <br>
<br>
=> chore: docker-compose.yaml 설정

app/db.py, app/init_db.py, app/main.py, app/models/__init__.py, app/models/board.py, app/routes/board.py, app/schemas/board.py, app/services/board_service.py, app/tests/test_boards.py, app/tests/test_user.py, requirements.txt
<br>
<br>
close #1
<br>
<br>
- 보드 관련 API 구현
- 테스트 코드
- requirements.txt 파일 수정
<br>
=> [feat] 보드 생성, 목록조회, 상세조회 구현

app/main.py, app/models/__init__.py, app/models/user.py, app/routes/__init__.py, app/routes/user.py, app/schemas/__init__.py, app/schemas/user.py, app/tests/test_signup.py, app/utils/__init__.py, requirements.txt
<br>
회원가입, 이메일 중복 확인 api 구현 
requirments.txt 에 pytz==2024.2 추가 datetime 한국으로 설정할떄 사용한 패키지
<br>
close #2 
<br>
<br>
- <br>
user model 생성
- <br>
<br>
=> feat: 회원가입 및 이메일 중복 확인

app/config.py, app/main.py, app/models/SelectedChannelsRequest.py, app/routes/auth.py, app/routes/channel.py, app/routes/subscriptions.py, app/utils/utils.py, requirements.txt
<br>
<br>
close #3
<br> 
<br>
- <br> Google 인증 및 리디렉션, 토큰 교환
- <br> YouTube API 호출
- <br> 응답 처리(채널 정보, 선택한 채널 ID 호출)
- <br>
<br>
=> feat: oauth 리다이렉트, 유튜브 구독 채널 목록 가져오기, 선택한 채널 정보 전송

app/config.py, app/models/user.py, app/routes/user.py, app/schemas/user.py, app/services/user_service.py, app/utils/__init__.py, app/utils/redis_handler.py, app/utils/time.py, docker-compose.yaml, requirements.txt
<br>
requirements에 PyJWT 추가 
로그인 로그아웃 구현 
레디스 파일 추가 
<br>
close #13 
<br>
<br>
- <br>
- <br>
<br>
=> [feat] 로그인, 로그아웃 구현, 레디스 생성 만듬

app/routes/user.py, app/services/user_service.py
<br>
회원가입, 로그인, 로그아웃 리팩토링함
<br>
close #23 
<br>
<br>
- <br>
- <br>
<br>
=> [refector] 회원가입, 로그인, 로그아웃 리팩토링함

app/routes/channel.py, app/routes/subscriptions.py
<br>
<br>
close #{22}
<br>
<br>
- <br> 선택한 채널 정보 호출 API(header error) 수정
- <br>
<br>
=> Refactor: 선택한 채널 정보 호출 API(header error) 수정

README.md, app/config.py, app/init_db.py, app/routes/channel.py, app/routes/subscriptions.py, app/routes/user.py, app/schemas/board.py, app/utils/__init__.py, docker-compose.yaml
<br>
<br>
close #29 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] DB 관련 오류 해결

app/routes/channel.py
<br>
<br>
close #{27}
<br>
<br>
- <br> 구독 채널 가져오기 로직 수정(구독 채널 출력, 각 채널의 동영상 목록 10개 출력)
- <br>
<br>
=> refactor: 구독 채널 가져오기 로직 수정

app/routes/channel.py, app/utils/redis_handler.py, docker-compose.yaml
<br>
redis에 유튜브동영상데이터 저장하는 것 구현
<br>
close #25 
<br>
<br>
- <br>
- <br>
<br>
=> [feat]redis에 유튜브데이터 저장 구현

app/main.py, app/routes/board.py, app/routes/user.py, app/schemas/board.py, app/schemas/user.py, app/services/auth.py, app/services/board_service.py, app/services/user_service.py, app/utils/jwt_handler.py, docker-compose.yaml, requirements.txt
<br>
<br>
close #31 
<br>
<br>
- 보드 목록 조회 시 권한 필요하도록 수정
- 보드 생성 시도 설정했으나 시험 못해봄
- JWT 관련 로그인 로직 수정
<br>
<br>
=> [feat] 보드 관련 API 토큰 사용하도록 수정

README.md, app/routes/channel.py, app/utils/redis_handler.py
<br>
<br>
close #36
<br>
<br>
- `video.list` API 호출하여 동영상 상세정보 redis에 저장하도록 구현
- 앞으로 ChatGPT 연동하여 가공된 데이터 응답하도록 수정할 필요 있음
<br>
- <br>
<br>
=> [feat] 동영상 상세 정보 가져오기 구현

app/main.py, app/models/board.py, app/routes/keyword.py, app/routes/share.py, app/schemas/board.py, app/schemas/gpt.py, app/services/board_service.py, app/utils/db_handler.py, app/utils/gpt_handler.py, app/utils/image_generator.py, app/utils/redis_handler.py, app/utils/redis_utils.py
<br>
<br>
close #33 
<br>
<br>
- <br> chatGPT 연동
- <br> 저장된 redis 데이터를 불러와 카테고리와 키워드 추출
- <br> 추출된 데이터 DB 저장
- <br> DB의 board 테이블에 카테고리 추가 
- <br> board 테이블의 keyword를 keywords 로 변경
<br>
=> feat: chatgpt 연동, 카테고리와 키워드 추출, 추출된 데이터 DB 저장

Dockerfile, README.md, app/config.py, app/main.py, app/routes/celery_tasks.py, app/routes/channel.py, app/services/celery_tasks.py, app/utils/celery_app.py, app/utils/redis_handler.py, docker-compose.yaml, requirements.txt
<br>
<br>
close #39 
<br>
<br>
- celery, rabbitmq 연동 완료
<br>
- Dockerfile, docker-compose.yaml 수정
<br>
<br>
=> [chore] celery, rabbitmq 연동 완료

.gitignore, app/models/board.py, app/routes/keyword.py, app/services/gpt_service.py, app/utils/db_handler.py
<br>
<br>
close #41 
<br>
<br>
- <br> DB 내용 수정(category 삭제, keywords 변경)
- <br>
<br>
=> refactor: DB 내용 수정

app/config.py, app/routes/auth.py
<br>
routes/auth.py
config.py
에 있는 oauth -> googleauth 로 변경 
노션 secret에 REDIRECT_URI도 수정함
<br>
close #45 
<br>
<br>
- <br>
- <br>
<br>
=> [refactor] oauth->googleauth 변경

app/routes/keyword.py, app/utils/db_handler.py, app/utils/gpt_handler.py
<br>
<br>
close #44 
<br>
<br>
- <br> keywords/{video_id} 엔드포인트 병합
- <br> 카테고리 및 키워드 추출 로직 변경 (모든 video_id를 list 형태로 참고하도록 프롬프트 변경)
- <br> 카테고리 비율 프롬프팅 포함, db에 저장 반영
- <br>
<br>
=> keyword 엔드포인트 병합, 카테고리 및 키워드 추출 로직 변경

app/services/board_service.py
<br>
<br>
close #51 
<br>
<br>
- <br>
- <br>
<br>
=> [refactor] 필요한 작업 주석 추가

app/routes/board.py, app/services/board_service.py, app/services/channel_service.py
<br>
channel_service.py 리팩토링함, board_service.py에 1~2번 구현함, route/board.py create_new-board에 create_board 삽입함
<br>
close #53 
<br>
<br>
- <br>
- <br>
<br>
=> [refactor] channel_service.py 리팩토링함

app/routes/board.py, app/utils/gpt_handler.py
<br>
알고리즘 일치율 계산 api 구현
gpt_handler에 match_board_ratio 구현
<br>
close #59 
<br>
<br>
- <br>
- <br>
<br>
=> [feat] 알고리즘 일치율 계산 api 구현

app/routes/board.py, app/schemas/board.py, app/services/board_service.py, app/services/user_service.py, app/tests/test_gcs.py, app/utils/dalle_handler.py, app/utils/gcs_handler.py, app/utils/redis_handler.py
<br>
<br>
close #58
<br>
<br>
- <br>
- <br>
<br>
=> [fix] 보드생성 api 수정

app/routes/board.py, app/utils/gpt_handler.py
<br>
알고리즘 일치율 계산 api 오류해결<br>
close #62 
<br>
<br>
- <br>
- <br>
<br>
=> fix: 알고리즘 일치율 계산 api 오류해결

app/routes/board.py
<br>
return 값에 category_ratio 추가
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
=> [feat] return 값에 category_ratio 추가

app/config.py, app/main.py, app/routes/profile.py
<br>
<br>
close #64 
<br>
<br>
- <br> 프로필 이미지 GCS 저장, url DB 저장
- <bt> 저장된 이미지 조회
- <br>
<br>
=> feat: 프로필 이미지 GCS 저장, url DB 저장, 이미지 조회

app/db.py, app/models/board.py, app/models/user.py, app/routes/board.py, app/routes/profile.py, app/services/board_service.py, app/tests/test_regenerate.py, app/utils/dalle_handler.py
<br>
<br>
close #70 
<br>
<br>
- <br> 프로필 이미지 put 로직 수정
- <br> user 테이블 상의 profile_img_url 추가
- <br> 이미지 재생성 로직 추가
- <br>
<br>
=> 프로필 조회 로직 수정, profile_img_url 추가, 이미지 재생성 추가

app/main.py
<br>
<br>
close #78
<br>
<br>
- <br>
- <br>
<br>
=> [fix] CORS 도메인 설정

app/routes/user.py
<br>
post -> get 수정
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
=> [fit] post -> get 수정

README.md, app/schemas/SelectedChannelsRequest.py, app/utils/dalle_handler.py, app/utils/gcs_handler.py
<br>
<br>
close #74 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] 이미지 생성 및 재생성 url 수정

app/main.py, docker-compose.yaml, requirements.txt
<br>
<br>
close #76 
<br>
<br>
- <br> requirement.txt에 prometheus 환경 변수 추가 (설치 필요)
- <br> main.py에 Instrumentator 라이브러리 추가 
- <br>
<br>
=> chore: prometheus 환경 추가

app/routes/auth.py, app/routes/profile.py
<br>
<br>
close #84 
<br>
<br>
- <br> 프로필 업로드 시 public url 생성으로 수정
- <br> googleauth redirect url 수정
- <br>
<br>
=> 프로필 업로드 시 public url 생성으로 수정, googleauth redirect url 수정

app/routes/board.py, app/schemas/board.py, app/services/board_service.py, docker-compose.yaml
<br>
<br>
close #86
<br>
<br>
- <br>
- <br>
<br>
=> [fix]: 보드생성 request body 수정

app/routes/auth.py, app/routes/profile.py
<br>
<br>
close #87 
<br>
<br>
- <br> 프로필 이미지, googleauth api 수정
- <br>
<br>
=> refactor: 프로필 이미지, googleauth api 수정

app/routes/auth.py, app/routes/subscriptions.py
<br>
<br>
close #{이슈넘버}
<br>
<br>
- <br> 리다이렉션 url 변경
- <br>
<br>
=> refactor: 리다이렉션 url 변경

app/routes/auth.py, app/routes/subscriptions.py
<br>
<br>
close #93 
<br>
<br>
- <br> googel_access_token 으로 변경
- <br>
<br>
=> refactor: 쿠키 수정

app/routes/board.py, app/services/board_service.py, docker-compose.yaml
<br>
<br>
close #97
<br>
<br>
- 응답에 보드 ID 포함
<br>
- <br>
<br>
=> [feat] 보드 생성 시 응답 수정

app/routes/profile.py, app/schemas/user.py
<br>
사용자 정보 가져오기 api 구현 완료
<br>
close #100 
<br>
<br>
- <br>
- <br>
<br>
=> [feat] 사용자 정보 가져오기 api 구현

app/routes/profile.py
<br>
유저정보 수정 후 유저정보 호출시 변경값 반영x 수정
<br>
close #102 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] 유저정보 수정 후 유저정보 호출시 변경값 반영x 수정

app/routes/auth.py, app/routes/subscriptions.py, app/services/google_service.py
<br>
<br>
close #95 
<br>
<br>
- <br> callback 함수에 채널 정보 조회 로직까지 포함, 리다이렉트 시 data_id={data_id} 변경
- <br>
<br>
=> refacotr: googleauth, channel-collect api 수정

app/services/board_service.py, app/services/channel_service.py, app/utils/gpt_handler.py, app/utils/redis_handler.py
<br>
<br>
close #106 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] redis에 hash 타입으로 youtube_video:{video_id} 저장하도록 변경

app/utils/gpt_handler.py
<br>
<br>
close #108 
<br>
<br>
- <br>
- <br>
<br>
=> [feat] 키워드 추출 1차 GPT 프롬프팅 개선

app/utils/gpt_handler.py
키워드 일치율 계산 프롬프트 수정 완료
<br>
<br>
close #110 
<br>
<br>
- <br>
- <br>
<br>
=> [Refactor] 키워드 일치율 계산 프롬프트 수정

app/services/board_service.py, app/utils/gpt_handler.py
<br>
보드이름 gpt생성 , 일치율 계산에 카테고리 출력 추가
<br>
close #{이슈넘버}
<br>
<br>
- <br>
- <br>
<br>
=> feat] 보드이름 gpt생성, 일치율 계산에 카테고리 출력 추가

app/services/board_service.py, app/utils/gcs_handler.py, app/utils/gpt_handler.py
<br>
<br>
이미지 생성 함수에서 url 부분, gcs_handler.py 업로드 부분 수정
close #116 
<br>
<br>
regenerate_image 함수  gcs업로드 부분 수정, gcs_handler.py 업로드 부분 수정 완료
- <br>
gpt 4o-mini로 업그레이드
- <br>
<br>
=> [fix] 이미지 생성 함수에서 url 부분, gcs_handler.py 업로드 부분 수정

app/routes/board.py, app/services/board_service.py, app/utils/gpt_handler.py
<br>
<br>
close #112
<br>
<br>
- ㅈㄱㄴ
<br>
- <br>
<br>
=> [feat] 카테고리별로 키워드 재생성 구현

app/routes/board.py, app/utils/gpt_handler.py
<br>
키워드 일치율 프로프팅 수정
<br>
close #118 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] 키워드 일치율 프로프팅 수정

app/routes/share.py
<br>
<br>
close #121 
<br>
<br>
- ㅈㄱㄴ
<br>
- <br>
<br>
=> [feat] UUID로 공유하도록 수정

app/utils/dalle_handler.py
<br>
<br>
close #105 
<br>
<br>
- <br> dall e 프롬프트 수정
- <br>
<br>
=> dall-e handler 프롬프트 수정

app/routes/board.py, app/utils/gpt_handler.py
<br>
<br>
close #125 
<br>
<br>
- ㅈㄱㄴ
<br>
- <br>
<br>
=> [feat] 알고리즘 일치율 계산 프롬프트 개선

app/main.py
<br>
<br>
close #130 
<br>
<br>
- /api/ 붙도록 수정
- <br>
<br>
=> [fix] route 수정

app/main.py, app/routes/__init__.py
<br>
<br>
close #132 
<br>
<br>
- <br>
- <br>
<br>
=> [fix] 라우터 재설정

app/config.py, app/routes/auth.py, app/utils/dalle_handler.py
<br>
config.py,auth.fy redirect url 수정 및 dalle 해상도 및 프롬프트 추가
<br>
close #129 
<br>
<br>
- <br>
- <br>
<br>
=> [feat] config.py,auth.fy redirect url 수정 및 dalle 해상도 및 프롬프트 추가
